# main text of home
name: Antonio Uccio Verardi
bio: "A guy who writes when he can't sleep. Software Engineer at <a href='http://www.yelp.com' target='_blank'>Yelp</a>"

# if it's an external image, update below for true
external-image: false
picture: 'assets/images/profile.jpg'

url: https://poros.github.io
# your url: http://USERNAME.github.io

permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics-google: 'UA-48109654-1'

# if you don't want comments in your posts, set to false
disqus: antoniouccioverardi

# if you don't have any of social below, comment the line
facebook: antonio.uccio.verardi
twitter: poros_7
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: antonioverardi
# youtube: myyoutube
# spotify: myspotify
github: poros
# medium: medium
email: antonio.uccio.verardi@gmail.com

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: false

gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
